#!/bin/sh
# Get the summary of a wikipedia entry

SEARCH=$(echo $* | tr ' ' '_')

curl -s "https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro&explaintext&redirects=1&titles=$SEARCH" | jq .query.pages[].extract
